import { ref } from "vue";

export const articles = ref([
  {
    id: 1,
    cover: null,
    title: "01234567890123456789012345678901234567890123456789",
    content:
      "Explore the new features of Drupal 8 and learn how to efficiently manage your site with Drupal's latest version. This guide will provide you with the necessary information to get started quickly.",
    authorId: 1,
    date: "20 minutes ago",
    tags: ["1234567890", "1111111111", "2222222222", "3333333333", "4444444444", "5555555555"],
    likes: 1000,
    replies: 1000,
    views: 1000,
  },
  {
    id: 2,
    cover: null,
    title: "Understanding React Hooks",
    content:
      "React hooks are a powerful new feature in React for sharing logic and state throughout your components. Learn the basics of useState and useEffect to make your React components more functional.",
    authorId: 2,
    date: "1 hour ago",
    tags: ["React", "JavaScript", "Web Development"],
    likes: 95,
    replies: 85,
    views: 308,
  },
  {
    id: 3,
    cover: "https://picsum.photos/id/3/900/400",
    title: "Introduction to Vue 3 Composition API",
    content:
      "Vue 3 brings an exciting new feature, the Composition API, which allows for better code organization and reuse. Discover how to use this API to enhance your Vue applications.",
    authorId: 3,
    date: "2 hours ago",
    tags: ["Vue", "JavaScript", "Frontend"],
    likes: 120,
    replies: 104,
    views: 400,
  },
  {
    id: 4,
    cover:
      "https://fastly.picsum.photos/id/4/900/400.jpg?hmac=ZeMVEnINnEmg7Vq571T0NNfByzzH3Wp5X36U_zIKHLk",
    title: "Advanced CSS Techniques",
    content:
      "Dive into advanced CSS techniques that can help you solve complex layout issues and enhance your web designs. Learn about grid layouts, flexbox, and custom properties (CSS variables).",
    authorId: 1,
    date: "3 hours ago",
    tags: ["CSS", "Web Design", "Frontend"],
    likes: 200,
    replies: 150,
    views: 520,
  },
  {
    id: 5,
    cover: "https://picsum.photos/id/5/900/400",
    title: "Getting started with Python",
    content:
      "Python is a versatile language that you can use for web development, data analysis, artificial intelligence, and more. Learn the basics of Python programming in this introductory guide.",
    authorId: 3,
    date: "5 hours ago",
    tags: ["Python", "Programming", "Data Science"],
    likes: 180,
    replies: 130,
    views: 450,
  },
  {
    id: 6,
    cover: "https://picsum.photos/id/6/900/400",
    title: "Building REST APIs with Node.js",
    content:
      "Node.js makes building efficient and scalable web services easier than ever. Learn how to build RESTful APIs with Node.js in this detailed tutorial.",
    authorId: 2,
    date: "Today",
    tags: ["Node.js", "Web Development", "API"],
    likes: 165,
    replies: 121,
    views: 390,
  },
  {
    id: 7,
    cover:
      "https://fastly.picsum.photos/id/7/900/400.jpg?hmac=D77S0XMH-yCk_BqNByQyvmk4AtrSK3XgF3HuUtA7tik",
    title: "Introduction to Machine Learning",
    content:
      "Machine learning is transforming the tech industry. Understand the basics of machine learning and how to implement simple models using Python.",
    authorId: 1,
    date: "Yesterday",
    tags: ["Machine Learning", "Python", "AI"],
    likes: 222,
    replies: 198,
    views: 580,
  },
  {
    id: 8,
    cover: "https://picsum.photos/id/8/900/400",
    title: "Principles of UI/UX Design",
    content:
      "Good design is essential for the success of a web application. Learn about the principles of UI/UX design and how to apply them to create engaging user experiences.",
    authorId: 2,
    date: "1 week ago",
    tags: ["Design", "UI", "UX", "Web Development"],
    likes: 143,
    replies: 134,
    views: 320,
  },
  {
    id: 9,
    cover: "https://picsum.photos/id/9/900/400",
    title: "Cloud Computing Basics",
    content:
      "Cloud computing offers powerful solutions to big data problems. Learn about the fundamentals of cloud computing and its applications in various industries.",
    authorId: 3,
    date: "2 weeks ago",
    tags: ["Cloud", "Technology", "Computing"],
    likes: 171,
    replies: 160,
    views: 430,
  },
  {
    id: 10,
    cover: "https://picsum.photos/id/10/900/400",
    title: "Cybersecurity Fundamentals",
    content:
      "Protecting information is crucial in the digital age. Discover the fundamentals of cybersecurity and learn how to safeguard your systems against cyber threats.",
    authorId: 1,
    date: "3 weeks ago",
    tags: ["Cybersecurity", "IT", "Security"],
    likes: 190,
    replies: 175,
    views: 500,
  },
  {
    id: 11,
    cover: "https://picsum.photos/id/11/900/400",
    title: "Exploring Data Structures in JavaScript",
    content:
      "Learn about various data structures used in JavaScript and their applications to enhance your coding skills and algorithmic understanding.",
    authorId: 2,
    date: "10 minutes ago",
    tags: ["JavaScript", "Data Structures", "Coding"],
    likes: 10,
    replies: 2,
    views: 50,
  },
  {
    id: 12,
    cover: "https://picsum.photos/id/12/900/400",
    title: "The Future of AI and Machine Learning",
    content:
      "Dive deep into the advancements and future prospects of AI and Machine Learning, and how they're shaping our technology landscape.",
    authorId: 3,
    date: "30 minutes ago",
    tags: ["AI", "Machine Learning", "Technology"],
    likes: 20,
    replies: 5,
    views: 120,
  },
  {
    id: 13,
    cover: "https://picsum.photos/id/13/900/400",
    title: "Introduction to Quantum Computing",
    content:
      "Quantum Computing is set to revolutionize our problem-solving capacities. Learn the basics of quantum mechanics and computing in this introductory article.",
    authorId: 3,
    date: "1 hour ago",
    tags: ["Quantum Computing", "Physics", "Innovation"],
    likes: 15,
    replies: 3,
    views: 75,
  },
  {
    id: 14,
    cover: "https://picsum.photos/id/14/900/400",
    title: "Understanding Cryptocurrency",
    content:
      "Explore the world of cryptocurrencies and how they operate under the hood, including the blockchain technology that powers them.",
    authorId: 3,
    date: "2 hours ago",
    tags: ["Blockchain", "Cryptocurrency", "Finance"],
    likes: 30,
    replies: 12,
    views: 200,
  },
  {
    id: 15,
    cover: "https://picsum.photos/id/15/900/400",
    title: "Getting Started with Docker",
    content:
      "Docker is a key tool for software deployment. This guide covers the basics of Docker, including its benefits and how to get started with containers.",
    authorId: 3,
    date: "Today",
    tags: ["Docker", "DevOps", "Software Deployment"],
    likes: 22,
    replies: 11,
    views: 160,
  },
  {
    id: 16,
    cover: "https://picsum.photos/id/16/900/400",
    title: "Web Security Essentials",
    content:
      "Understanding web security is crucial for developers. Learn about common security threats and how to protect your applications.",
    authorId: 3,
    date: "Yesterday",
    tags: ["Web Security", "Cybersecurity", "Development"],
    likes: 25,
    replies: 9,
    views: 140,
  },
  {
    id: 17,
    cover: "https://picsum.photos/id/17/900/400",
    title: "Advanced JavaScript Techniques",
    content:
      "Take your JavaScript skills to the next level with these advanced techniques that can help you write cleaner and more efficient code.",
    authorId: 3,
    date: "1 week ago",
    tags: ["JavaScript", "Advanced", "Programming"],
    likes: 40,
    replies: 20,
    views: 300,
  },
  {
    id: 18,
    cover: "https://picsum.photos/id/18/900/400",
    title: "Exploring the Angular Framework",
    content:
      "Discover the features of Angular and how it differs from other JavaScript frameworks to build powerful and dynamic web applications.",
    authorId: 3,
    date: "2 weeks ago",
    tags: ["Angular", "Web Development", "Framework"],
    likes: 18,
    replies: 7,
    views: 110,
  },
  {
    id: 19,
    cover: "https://picsum.photos/id/19/900/400",
    title: "The Rise of Mobile Gaming",
    content:
      "Mobile gaming continues to grow at an unprecedented rate. Understand the factors driving this growth and the future of the industry.",
    authorId: 3,
    date: "3 weeks ago",
    tags: ["Gaming", "Mobile", "Technology"],
    likes: 50,
    replies: 25,
    views: 400,
  },
  {
    id: 20,
    cover: "https://picsum.photos/id/20/900/400",
    title: "Effective Project Management Strategies",
    content:
      "Project management is key to successful software development. Learn about effective strategies and tools to manage your projects efficiently.",
    authorId: 3,
    date: "1 month ago",
    tags: ["Project Management", "Software Development", "Strategy"],
    likes: 35,
    replies: 15,
    views: 250,
  },
]);
